### ISSUE TITLE
feature request: allow HTTP method specification for notification URLs

### ISSUE THREAD

**Issue by dsw9742** [docker-flow/docker-flow-swarm-listener#20]
Skimming the present code, it appears as though all requests from DFSL to another endpoint are made using the HTTP GET method. It would be nice to be able to specify which HTTP method to use for each value provided to configuration URLs, e.g. if I had three comma-separated values provided to DF_NOTIFY_CREATE_SERVICE_URL then I could override the default GET method by specifying the corresponding values like `DF_NOTIFY_CREATE_SERVICE_METHOD=GET,POST,GET`. We are trying to notify Jenkins on Docker Swarm service and node state changes and its API requires the use of POST methods.

**Comment by thomasjpfan** [comment]
I will look into this feature request.

**Comment by thomasjpfan** [comment]
I added this feature in `dockerflow/docker-flow-swarm-listener:18.07.22-30`. Please test it out and see if it works for you.
