### ISSUE TITLE
feature request: secrets for credentials in notification requests

### ISSUE THREAD

**Issue by dsw9742** [docker-flow/docker-flow-swarm-listener#21]
Current DFSL API requires basic authentication credentials be included in clear-text in the values provided to the notification URLs, e.g. `--env DF_NOTIFY_CREATE_SERVICE_URL=http://username:passwordortoken@test.org/service/createOrUpdate`. It would be ideal if credentials could be provided in a more secure manner, perhaps using Docker secrets instead, e.g. similar to [how DFP handles sensitive information](https://proxy.dockerflow.com/swarm-mode-auto/#service-authentication).

**Comment by thomasjpfan** [comment]
I propose the following implementation:

DFSL will look for a secret named `df_notify_create_service_url` which contains a comma separated list of urls. These urls will be added to the list of urls DFSL is sending create notifications to. The other secrets will be named `df_notify_remove_service_url`, `df_notify_create_node_url `, `df_notify_remove_node_url`.

@dsw9742 What do you think?

**Comment by dsw9742** [comment]
This is much better than my suggestion. I think it sounds great

**Comment by thomasjpfan** [comment]
@dsw9742 This feature was added in `dockerflow/docker-flow-swarm-listener:18.08.01-31`. Please test it out and see if it works for your use case.
