### ISSUE TITLE
Feature Request: option to pass more labels in removal notification

### ISSUE THREAD

**Issue by anomaly256** [docker-flow/docker-flow-swarm-listener#23]
Hi, I'm currently using docker flow swarm listener to trigger some additional actions via http on service creation/removal. However I notice it doesn't pass the additional com.df.* labels I'm using on service removal. Is it possible to add this as an option?  Or is it a limitation of docker that swarm listener can't see the additional labels at that point?

Thanks

**Comment by thomasjpfan** [comment]
DFSL does hold on to the service labels, so it is technically possible to send the `com.df.*` labels during service removal. What are you planning to do with the labels during service removal?

**Comment by anomaly256** [comment]
Well for example, currently I have an http endpoint in DF_NOTIFY_CREATE_SERVICE_URL which uses additional com.df.* labels to add dns records to an internal dev dns zone; the host, record type, and data are defined by the values of the labels when a service is deployed.  This is working pretty well.  It would be nice to have DF_NOTIFY_REMOVE_SERVICE_URL pass the labels through the query string as well so the same mechanism can remove now-stale records and put the zone back how it was before the deployment without having to track this information separately.

I could come up with other uses where this would be handy as well.  Basically anything like the above where additional com.df labels are used to configure a service dynamically and you want the service definition to remain the sole source of truth, but said service or the api handler in front of it doesn't have access to the docker environment except through the http calls DFSL makes and you don't want to add reliance on a database to keep track of that data against the serviceName.

**Comment by thomasjpfan** [comment]
Thank you for the information!

I have updated DFSL to include `com.df.*` labels in remove notifications. You can test out this feature with `dockerflow/docker-flow-swarm-listener:18.08.20-32`.

**Comment by anomaly256** [comment]
Thanks!  I'll give it a try today

**Comment by anomaly256** [comment]
Works perfectly, thanks again

**Comment by anomaly256** [comment]
Hi @thomasjpfan, in testing I discovered that a query param I add to the remove URL isn't being passed through, while one in the create URL is, then I noticed #19 and 415d30f which recently added this to Create().  Would it be ok to have this applied to the Remove() func as well?

**Comment by thomasjpfan** [comment]
Your requested feature has been added to `dockerflow/docker-flow-swarm-listener:18.08.22-33`. Please test it out and see if it works for your use case.

**Comment by anomaly256** [comment]
Yep, perfect.  Thanks yet again, appreciated
