### ISSUE TITLE
A new cluster

### ISSUE THREAD

**Issue by vfarcic** [docker-flow/docker-flow-swarm-listener#26]
@thomasjpfan I'm in the process of moving everything to a new cluster (GCE). For now, Jenkins running in that cluster is accessible through http://jenkins2.dockerflow.com. At the moment, only `docker-flow-swarm-listener` job is moved there.

**Comment by thomasjpfan** [comment]
Thank you for the update!

**Comment by vfarcic** [comment]
All the apps are transitioned. The only important difference is that Jenkins address is now jenkins2.dockerflow.com.

**Comment by thomasjpfan** [comment]
@vfarcic Can you update Jenkins to allow PRs to be tested?

**Comment by vfarcic** [comment]
It's done. You'll have to push a dummy commit to that PR to start a build.
