### ISSUE TITLE
How can i send a notification after Rolling update completes

### ISSUE THREAD

**Issue by caryyu** [docker-flow/docker-flow-swarm-listener#4]
As title said.

**Comment by vfarcic** [comment]
Can you please describe your use case. Normally, I'd execute rolling update in attached mode (it's the default for a while). The command would return an exit code once all the replicas converged and, depending on that exit code I'd to one action or another. In my case that done through Jenkins as part of CD processes but the same logic should work in any other tool (e.g., Travic, CircleCI, CodeShip, etc.). 

If you can explain your use case, we can brainstorm the best way to accomplish it. That might be through changes to DFSL or some other mechanism.

**Comment by caryyu** [comment]
@vfarcic Thanks for replying , It seems like  command option `--detach` of `docker service update` is good enough to reach my situation, close the issue.
