### ISSUE TITLE
HTTPS notifications fail

### ISSUE THREAD

**Issue by jmorenoamor** [docker-flow/docker-flow-swarm-listener#43]
**Description**

When sending notifications to HTTPS endpoints, swarmlistener does not recognize the certificate and keeps retrying

```
Retrying service created notification to https://jsonplaceholder.typicode.com/posts/1?distribute=***************************
Get https://jsonplaceholder.typicode.com/posts/1?distribute=**********************: x509: certificate signed by unknown authority
Unable to send ServiceCreateNotify to https://jsonplaceholder.typicode.com/posts/1, params: *********************
```

This happens with correct certificates.

**Steps to reproduce the issue:**
1. Set notification URL to Retrying service created notification to https://jsonplaceholder.typicode.com/posts/1

**Describe the results you received:**

```
Retrying service created notification to https://jsonplaceholder.typicode.com/posts/1?distribute=***************************

Get https://jsonplaceholder.typicode.com/posts/1?distribute=**********************: x509: certificate signed by unknown authority
Unable to send ServiceCreateNotify to https://jsonplaceholder.typicode.com/posts/1, params: *********************

```

**Describe the results you expected:**

OK

**Additional information you deem important (e.g. issue happens only occasionally):**

NA

**Additional environment details (AWS, VirtualBox, physical, etc.):**

NA

**Comment by vfarcic** [comment]
The project is not maintained anymore. It's been years since the last release. Essentially, Docker Swarm died a while ago, most of its users moved to Kubernetes so there was no need anymore to keep this project running.

**Comment by jmorenoamor** [comment]
Ok, thanks,
