### ISSUE TITLE
Docker version(s) tested for Docker Flow services

### ISSUE THREAD

**Issue by dsw9742** [docker-flow/docker-flow-swarm-listener#7]
This is a question more than anything else. When tests are run against Docker Flow services (including DFSL but also DFP and DFM, since there are "dependencies" amongst them), which against which versions of Docker are they tested?

I ask because I was browsing the Docker for Linux issues recently in relation to [DFSL issue #3](https://github.com/docker-flow/docker-flow-swarm-listener/issues/3), and I noticed an [issue filed about memory leaks in 18.03.1-ce](https://github.com/docker/for-linux/issues/304), and it got me wondering if these are related. Even if they aren't, now I'm curious how tests and versions work for the Docker Flow stack of services.

**Comment by dsw9742** [comment]
Yes, of course, that is completely reasonable! Is it the latest stable version, the latest edge version, or does it vary?

**Comment by vfarcic** [comment]
It's the latest stable version.

VMs are created from AMIs built with Packer. The definition is in https://github.com/vfarcic/docker-flow-hub/blob/master/packer/test-cluster.json.

I just built a new image so, starting from the next commit, it'll be Docker 18.03.

**Comment by vfarcic** [comment]
I'm not sure what you mean by adding the information to DFSL Dockerfile. It does not use any specific Docker version.

**Comment by dsw9742** [comment]
I was thinking something like a `LABEL com.df.testedDockerVersion=v18.03.1-ce` in the Dockerfile ... in hindsight, I'm not really sure how useful that would be. If anything would be a concern as it relates to Docker version, it would probably be the Docker API version in use ... and even then, I'm not sure how much that would matter, since Docker has communicated that they basically expect users to be no more than one stable release behind the current stable release.

Feel free to close this. Was trying to offer a helpful suggestion but its actually just more confusing.
