### ISSUE TITLE
No events sent when a service replica change in global replica mode

### ISSUE THREAD

**Issue by Munchery-DavidMichon** [docker-flow/docker-flow-swarm-listener#9]
I'm using it with docker-flow-monitor and flexible labeling. When I create a new node on the swarm, an event is correctly sent to DF_NOTIFY_CREATE_NODE_URL. However, as I have some exporters configured as global, no event is sent to DF_NOTIFY_CREATE_SERVICE_URL. It's a problem as these new replicas do not appears in targets and thus do not scrape metrics.

**Steps to reproduce the issue:**
1. Setup the stack and node-exporter as replica mode global
2. Add a new node to the stack

**Describe the results you received:**
I only see this event but no event for services that add new instances.
```
monitor_monitor-swarm-listener.1.q8vu6fuqdr8z@swarm-manager-2    | 2018/05/25 12:33:19 Sending node created notification to http://monitor:8080/v1/docker-flow-monitor/node/reconfigure?address=192.168.99.107&availability=active&hostname=swarm-worker-3&id=hxzf579q0guyqsz722iixpj7q&role=worker&state=ready&versionIndex=795`
```

<img width="895" alt="screen shot 2018-05-25 at 09 48 16" src="https://user-images.githubusercontent.com/38669171/40545262-9f7b74a2-6001-11e8-8647-7784362776f8.png">

<img width="1369" alt="screen shot 2018-05-25 at 09 48 29" src="https://user-images.githubusercontent.com/38669171/40545263-a2732cae-6001-11e8-968d-d1250aa6a29d.png">

**Describe the results you expected:**
I expected an event to be fired for each services that add a replica.

**Additional information you deem important (e.g. issue happens only occasionally):**
I believe targets are updated properly on docker-flow-monitor if used with `dns_sd_config` instead of `file_sd_config` 

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm testing it on VirtualBox

**Comment by Munchery-DavidMichon** [comment]
Note that a `docker-service update` actually resolve the issue. So I imagine that I would need to add this in the pipeline if I handle scaling with Jenkins. Do [Docker Flow Scaler](http://scaler.dockerflow.com/) actually handle this use-case?

**Comment by thomasjpfan** [comment]
Can you test out `thomasjpfan/docker-flow-swarm-listener:6f2ff36` for your use case?

**Comment by Munchery-DavidMichon** [comment]
@thomasjpfan thanks for your prompt response. I'll test it next Monday and keep you informed.

**Comment by thomasjpfan** [comment]
My fix does not work. I will take another look at this.

**Comment by thomasjpfan** [comment]
I have updated DFSL to send service notifications after sending node notifications. You can test this feature out in `dockerflow/docker-flow-swarm-listener:18.05.27-13`.

**Comment by Munchery-DavidMichon** [comment]
@thomasjpfan I tested and it works perfectly! 👍 

As a side note, and it's related to docker and not to docker-flow-swarm-listener, when a node is put down, services in replica mode global also scale down. This means that if we rely on prometheus targets "up" status to detect unavailable nodes it never works.

<img width="955" alt="screen shot 2018-05-28 at 08 34 25" src="https://user-images.githubusercontent.com/38669171/40612720-148546cc-6252-11e8-9044-6bb9d1ce1d71.png">

<img width="877" alt="screen shot 2018-05-28 at 08 34 39" src="https://user-images.githubusercontent.com/38669171/40612734-1c2fb808-6252-11e8-9abd-7dcd17e8808c.png">

<img width="1018" alt="screen shot 2018-05-28 at 08 34 49" src="https://user-images.githubusercontent.com/38669171/40612740-20ba99a6-6252-11e8-9ba1-9b79fe99b31b.png">

**Comment by thomasjpfan** [comment]
@Munchery-DavidMichon When a node is drained or goes down, DFSL will notify DFM on the updated list of running exporters. That means the exporter on the drained/down node will be removed from the target list.

Theoretically, if DFM was setup to keep metrics from downed nodes, that target list will become larger through time. What would be a good indicator to remove the metric from the list?

**Comment by Munchery-DavidMichon** [comment]
I strongly believe that DFM and DFSL works exactly the way we expect them to work because it reflect exactly what docker API gives.

In my opinion the issue is more on docker. When you set a service as global and a node is down, the service replicas should be in a state 5/6 (in my case), and not 5/5. I mean, I want a global deployment of my services so 1 for every node of my cluster. My cluster count effectively 6 nodes, not all in `Ready` state but 6 are `Active` in their availability.

The problem here is that DFM remove metrics (correctly) because it understands that he has 5 targets to track to, so all are up. I would not change anything to DFM to keep metrics for downed nodes. It's correct in its design and implementation. 

I need to detect in another way that a node is down. Perhaps another exporter that do just that, export nodes status and availability as metrics.

**Comment by dsw9742** [comment]
@Munchery-DavidMichon I'm following this now, since we're interested in this problem as well. I'm curious if you can get [docker-socat](https://github.com/bvis/docker-socat) running in your stack, and if the [Docker metrics](https://docs.docker.com/config/thirdparty/prometheus/) it presents contain the right info to solve for this use-case. We have not been able to successfully deploy docker-socat in our stack, but if others are able to do so successfully, we would love to be able to learn from them ...

**Comment by dsw9742** [comment]
@Munchery-DavidMichon thanks for the write-up! I will be sure to pass this along to our team for feedback.

**Comment by Munchery-DavidMichon** [comment]
We can consider this issue resolved.
